app:
  tg_bot_token: YOUR_TG_BOT_TOKEN
  path_to_id_rsa: path/to/your/id_rsa
  port: 8080

servers:
  - host: 127.0.0.1                     # хост для подключения
    port: 22                            # порт для подключения
    user: root                          # пользователь для подключения
    notify: true                        # отправлять уведомления при уровне ERROR
    is_local: false                     # локальный сервер или удаленный
    start_line: 0                       # строка с которой начинается чтение логов
    log_dir: path/to/your/file.log      # путь к файлу с логами
    chat_ids: [ YOUR_TG_CHAT_IDS_HERE ] # айди чатов, которым будут приходить уведомления
    last_notify_line: 0                 # ДАННОЕ ЗНАЧЕНИЕ МЕНЯТЬ НЕЖЕЛАТЕЛЬНО.
    # Оно используется для сохранения последнего лога с уведомлением.
    # Чтобы не приходили повторные уведомления - не трогайте это поле

# (keywords) - ключи в логах,
# которые могут в ваших логах иметь ту же цель, но другое название
keywords:
  # (time) - время создания лога
  time: time
  # (info) - какая то общая информация о логе прогарммы.
  # пример - версия, пид или версия языка, используемая для билда
  info: program_info
  # (lvl) - уровень лога, например INFO или ERROR
  lvl: level
  # (msg) - само сообщение в логе
  msg: message
  # (err) - массив стектрейса с ошибкой
  err: error
  # (src) - место в котором был вызван лог
  src:
    source: source # название массива с `src`
    func: function # ключ с хранением пути к функции
    file: file     # ключ с храненением пути к файлу
    line: line     # ключ со строкой вызова лога
