app:
  tg_bot_token: YOUR_TG_BOT_TOKEN       # токен вашего тг бота
  path_to_id_rsa: path/to/your/id_rsa   # путь до вашего id_rsa
  port: 8080                            # порт веб сервера
  max_local_log_size_mb: 10             # максимальный размер локально сохранненных логгов
  number_rows_to_load: 100              # колво строк, которое загружается при подключении

# любой параметр из настроек серверов можно вынести в общие настройки
# внесенное поле можно переназначить для любого из серверов
default_servers_setting:
  log_levels: "(ERROR)"
  log_time_format: "YYYY-MM-DD HH:mm:SS"

servers:
  - enabled: true                               # включена ли эта проверка
    name: Test remote server                    # название проверки
    host: 127.0.0.1                             # хост для подключения
    port: 22                                    # порт для подключения
    user: root                                  # пользователь для подключения
    notify: true                                # отправлять уведомления при уровне ERROR
    is_local: false                             # локальный сервер или удаленный
    start_line: 0                               # строка с которой начинается чтение логов
    log_dir: path/to/your/file.log              # путь к файлу с логами
    log_layout: "%TIME %LEVEL% %MESSAGE%"       # шаблон, по которому будем искаться уровень лога в строке
    log_levels: "ERROR|WARN"                    # уровни логов при котором нужно делать оповещение
    log_time_format: "DD.MM.YYYY HH:mm"         # формат времени в строке логов
    chat_ids: [ YOUR_TG_CHAT_IDS_HERE ]         # айди чатов, которым будут приходить уведомления

  # пример подключения нескольких локальных лог файлов
  # такая же логика работает и для удаленных серверов
  - enabled: false
    name: First local server,Second local server
    is_local: true
    notify: true
    start_line: 0
    log_dir: path/to/your/first/file.log path/to/your/second/file.log
    log_layout: "lvl=%LEVEL% msg=%MESSAGE%"
    chat_ids: [ YOUR_TG_CHAT_IDS_HERE ]
