app:
  debug: false                          # true - позволяет увидеть больше логов при работе приложения
  tg_bot_token: YOUR_TG_BOT_TOKEN       # токен вашего тг бота
  path_to_id_rsa: path/to/your/id_rsa   # путь до вашего id_rsa для подключения к удаленным серверам
  port: 8080                            # порт веб сервера
  max_local_log_size_mb: 10             # максимальный размер локально сохраненных логов
  number_rows_to_load: 100              # количество строк, которое загружается при подключении в браузере
                                        # большое количество может привести к лагам
  auth: false                           # поле, которое отвечает за то, нужна ли ограничивать доступ другим пользователям
                                        # см. README.md

# любой параметр из настроек серверов можно вынести в общие настройки
# (такая настройка будет по умолчанию у всех серверов)
# внесенное поле можно переназначить для любого из серверов
default_servers_setting:
  start_line: 0
  log_levels: "ERROR"
  notify: "telegram"
  log_time_format: "YYYY-MM-DD hm:mm:ss"
  recipients: [ "YOUR_TG_CHAT_IDS_HERE" ]

servers:
  - id: 0                                       # айди может быть произвольным (id >= 0)
    enabled: false                              # включена ли эта проверка
    name: Test remote server                    # название проверки
    host: 127.0.0.1                             # хост для подключения
    port: 22                                    # порт для подключения
    user: root                                  # пользователь для подключения
                                                # (см. README.md чтобы узнать, что нужно для входа на удаленный сервер)
    notify: "mb_your_driver"                    # отправлять уведомления при указанном уровне лога (см. `log_levels`)
    is_local: false                             # локальный сервер или удаленный
    start_line: 0                               # строка с которой начинается чтение логов
    log_dir: path/to/your/file.log              # путь к файлу с логами
    log_layout: "%TIME %LEVEL% %MESSAGE%"       # шаблон, по которому будем искаться уровень лога в строке
    log_levels: "ERROR|WARN"                    # уровни логов при котором нужно делать оповещение
                                                # при нескольких уровнях - указывайте через '|'
    log_time_format: "DD.MM.YYYY hh:mm"         # формат времени в строке логов
    recipients: [ "ANOTHER_TG_CHAT_IDS" ]         # айди чатов, которым будут приходить уведомления

  # пример подключения нескольких локальных лог файлов
  # такая же логика работает и для удаленных серверов
  - id: 9
    enabled: false
    name: First local server,Second local server # при указании нескольких серверов - указывать их через запятую
    is_local: true
    log_dir: path/to/your/first/file.log path/to/your/second/file.log
    log_layout: "lvl=%LEVEL% msg=%MESSAGE%"     # шаблон один, который работает на оба сервера

  - id: 52
    enabled: false
    name: json logs 
    is_local: true
    log_dir: path/to/your/first/file.json 
    log_driver: "your_custom_driver_name"
    log_time_format: "YYYY-MM-DD hh:mm:ss"
    log_levels: "WARNING|ERROR"
    log_layout: "\\[%TIME%\\] %LEVEL% %MESSAGE%"


